services:
  mycoverai:
    build:
      dockerfile: Dockerfile
      context: .
      # Will only build development stage from the dockerfile
      target: development
    container_name: mycoverai
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 5090:5090
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - mycoveraidb:/var/lib/postgresql/data
    env_file:
      - docker.env
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - mycoveraiadmin:/root/.pgadmin
    env_file:
      - docker.env
    depends_on:
      - postgres
volumes:
  mycoveraidb:
  mycoveraiadmin: